version: 2
jobs:
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Prepare packages
          command: yarn bootstrap
      - run:
          name: Test packages
          command: yarn test
  publish:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Prepare packages
          command: yarn bootstrap
      - run:
          name: Release packages
          command: yarn release
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
