version: 2.0

dependencies:
  pre:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

jobs:
  test:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Test packages
          command: yarn test
      - run:
          name: Get coverage of packages
          command: yarn coverage
  publish:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Release packages
          command: |
            git config --global github.token $GH_TOKEN
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_USER
            yarn release

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
