version: 2.0
jobs:
  test:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Prepare packages
          command: yarn bootstrap
      - run:
          name: Test packages
          command: yarn test
  coverage:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Prepare packages
          command: yarn bootstrap
      - run:
          name: Get coverage of packages
          command: yarn coverage
  publish:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Prepare packages
          command: yarn bootstrap
      - run:
          name: Release packages
          command: yarn release
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - coverage:
          requires:
            - test
      - publish:
          requires:
            - test
            - coverage
          filters:
            branches:
              only: master
