version: 2.0

jobs:
  test:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: npm install
      - run:
          name: Test packages
          command: npm run test
      - run:
          name: Get coverage of packages
          command: npm run coverage
  publish:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: npm install
      - run:
          name: Setup NPM and Github credentials
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            git config --global github.token $GH_TOKEN
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_USER
      - run:
          name: Release packages
          command: npm run release

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
