version: 2.0
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Test packages
          command: yarn test
      - run:
          name: Get coverage of packages
          command: yarn coverage

  publish:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run:
          name: Install monorepo
          command: yarn install
      - run:
          name: Release packages
          command: yarn publish
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
