version: 2
jobs:
  dryrun:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Perform dryrun on Label Sync
          command: yarn sync --dryrun
  sync:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Perform sync of labels
          command: yarn sync
workflows:
  version: 2
  sync-labels:
    jobs:
      - dryrun
      - hold:
          type: approval
          requires:
            - dryrun
      - sync:
          requires:
            - hold
